sudo: required
services:
  - docker

before_install:
  - docker build -t bgahavan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bgahavan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "daka"
  env: "Daka-env"
  bucket_name: "elasticbeanstalk-eu-central-1-349214397958"
  bucket_path: "daka"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY